### ISSUE TITLE
Verify that Binospec off-axis aberrations are being applied correctly.

### ISSUE THREAD

**Issue by bamcleod** [MMTObservatory/mmtwfs#21]
Using data taken during Bino run, determine correct rotation for off-axis aberrations.

**Comment by tepickering** [comment]
this has been verified against on-axis CWFS observations since the binospec WFS was fixed. on-axis CWFS and off-axis SHWFS now give the same results so the predicted off-axis aberration model is being correctly applied and subtracted.
